---

- name: install dependencies apt packages
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
    update_cache: yes
    cache_valid_time: 86400
  with_items: "{{ vault_dep_packages }}"

- name: check install, data & config directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ vault_install_dir }}"
    - "{{ vault_config_dir }}"
    - "{{ vault_data_dir }}"

- name: "download vault"
  get_url:
    url: "{{ vault_tarball_url }}"
    dest: "{{ vault_tmp_full_path }}"
    owner: root
    group: root
    mode: 0755
  register: vault_download

- name: extract vault
  unarchive:
    src: "{{ vault_tmp_full_path }}"
    dest: "{{ vault_install_dir }}"
    owner: root
    group: root
    mode: 0755
    remote_src: yes
#  notify: restart vault
  when: vault_download|changed

- name: config
  template:
    src: config.hcl.j2
    dest: "{{ vault_config_dir }}/config.hcl"
#  notify: restart vault
  tags: vault_config
